apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appNavn}}
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  secureLogs:
    enabled: true
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  {{#if erAssistent}}
  filesFrom:
    - secret: k9-vaktmester-srvusercredentials
      mountPath: /var/run/secrets/nais.io/service_user
  {{/if}}
  {{#if erVaktmester}}
  kafka:
    pool: {{KAFKA_POOL}}
  {{/if}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
    - name: KAFKA_CONSUMER_GROUP_ID
      value: k9-vaktmester