apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-vaktmester
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        diskAutoresize: true
        tier: {{ database.tier }}
        highAvailability: {{ database.highAvailability }}
        databases:
          - name: k9-vaktmester
            envVarPrefix: DATABASE
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{kafkaPool}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
    - name: KAFKA_CONSUMER_GROUP_ID
      value: k9-vaktmester
    - name: KAFKA_RAPID_TOPIC
      value: omsorgspenger.k9-rapid-v2