CREATE TABLE IN_FLIGHT
(
    BEHOVSSEKVENSID VARCHAR(100) NOT NULL,
    SIST_ENDRET DATE NOT NULL,
    BEHOVSSEKVENS JSONB NOT NULL,
    PRIMARY KEY(BEHOVSSEKVENSID, SIST_ENDRET)
);

CREATE TABLE ARKIV
(
    BEHOVSSEKVENSID VARCHAR(100) PRIMARY KEY,
    BEHOVSSEKVENS JSONB NOT NULL
);
