CREATE TABLE IN_FLIGHT
(
    BEHOVSSEKVENSID VARCHAR(100) PRIMARY KEY,
    SIST_ENDRET TIMESTAMP WITH TIME ZONE NOT NULL,
    BEHOVSSEKVENS JSONB NOT NULL,
    OPPRETTETTIDSPUNKT TIMESTAMP WITH TIME ZONE default (now() at time zone 'utc')
);

CREATE TABLE ARKIV
(
    BEHOVSSEKVENSID VARCHAR(100) PRIMARY KEY,
    BEHOVSSEKVENS JSONB NOT NULL,
    ARKIVERINGSTIDSPUNKT TIMESTAMP WITH TIME ZONE NOT NULL default (now() at time zone 'utc')
);
